Repository process-analytics/pa-technical-challenge, pull requests merged in 2021-05, with the labels that each got.

#4 [DOC] Fill the empty section in main README
  README.md
Labels: documentation

#5 [DOC] Add bingo rules
  README.md
Labels: documentation

#7 [TEST] Add empty test for ts-rollup challenge
  .gitignore
  library/ts-rollup/dev/index.ts
  library/ts-rollup/package-lock.json
  library/ts-rollup/package.json
  library/ts-rollup/rollup.config.js
  library/ts-rollup/src/index.ts
  library/ts-rollup/test/e2e/__image_snapshots__/something-test-ts-test-something-should-initialize-grid-when-1-snap.png
  library/ts-rollup/test/e2e/jest-playwright.config.js
  library/ts-rollup/test/e2e/jest.config.js
  library/ts-rollup/test/e2e/something.test.ts
  library/ts-rollup/test/unit/something.test.ts
  library/ts-rollup/tsconfig.json
Labels: infra:build

#6 [DOC] Improve the main readme
  README.md
Labels: documentation

#11 [DOC] Update library build commands list
  library/es-webpack/README.md
  library/ts-rollup/README.md
Labels: documentation

#12 [FEAT] Add the API to reset the grid on TypeScript challenge
  README.md
  images/grid.png
  images/start_library_rendering.png
  library/ts-rollup/README.md
  library/ts-rollup/dev/index.html
  library/ts-rollup/dev/index.ts
  library/ts-rollup/dev/static/css/main.css
  library/ts-rollup/package.json
  library/ts-rollup/rollup.config.js
  library/ts-rollup/src/graph.ts
  library/ts-rollup/src/index.ts
  library/ts-rollup/test/unit/something.test.ts
Labels: enhancement

#10 [DOC] Simplify questions
  README.md
Labels: documentation

#13 [FEAT] Add the API to update the background color of a square on TypeScript challenge
  README.md
  images/background-color.png
  images/start_library_rendering.png
  library/ts-rollup/README.md
  library/ts-rollup/dev/index.html
  library/ts-rollup/dev/index.ts
  library/ts-rollup/dev/static/css/main.css
  library/ts-rollup/src/index.ts
Labels: enhancement

#15 [FEAT] Add new API to add an handler on the grid
  README.md
  library/ts-rollup/README.md
  library/ts-rollup/dev/index.ts
  library/ts-rollup/src/index.ts
Labels: enhancement

#14 [FEAT] Update Javascript challenge
  library/es-webpack/README.md
  library/es-webpack/dev/index.html
  library/es-webpack/dev/index.js
  library/es-webpack/dev/static/css/main.css
  library/es-webpack/src/graph.js
  library/es-webpack/src/index.js
Labels: enhancement
